#!/bin/bash

# List of packages
packages=(
  nano # Console text editor
  kitty # Terminal
  hyprland # Tiling Wayland compositor
  hyprpaper # Wallpaper utility
  hyprlock # Screen locker
  xdg-desktop-portal-hyprland # XDG portal for Wayland apps
  sddm # Display manager
  flatpak # Package manager for sandboxed apps
  waybar # Wayland status bar
  nautilus # File manager
  wofi # Application launcher
  mako # Notification daemon
  git # Version control system
)

# Update the system
sudo pacman -Syu --noconfirm

# Install the packages
sudo pacman -S "${packages[@]}" --noconfirm

# Enable the display manager to start on boot
sudo systemctl enable sddm # Enable sddm

# -------- Locale --------
# Find and uncomment the line for ru_UA.UTF-8 in /etc/locale.gen
sudo sed -i '/^#\s*ru_UA\.UTF-8/s/^#\s*//' /etc/locale.gen

# Generate the locales
sudo locale-gen
# -------- End Locale --------

# -------- Display a message before the Hyprland setup --------
echo "Starting Hyprland setup..."
CONFIG_FILE="$HOME/.config/hypr/hyprland.conf"
BACKUP_FILE="${CONFIG_FILE}.bak-$(date +%Y-%m-%d_%H-%M-%S)"

# Create a backup of the configuration file
if [ -f "$CONFIG_FILE" ]; then
    cp "$CONFIG_FILE" "$BACKUP_FILE"
    echo "Backup created: $BACKUP_FILE"
else
    echo "Error: Configuration file not found at $CONFIG_FILE"
    exit 1
fi

# Remove warning message
sed -i 'autogenerated/#autogenerated/' "$CONFIG_FILE"

# Modify kb_layout
sed -i 's/kb_layout = us/kb_layout = us,ru/' "$CONFIG_FILE"

# Modify kb_options
sed -i 's/kb_options =/kb_options = grp:alt_space_toggle/' "$CONFIG_FILE"

# Modify natural_scroll
sed -i 's/natural_scroll = false/natural_scroll = true/' "$CONFIG_FILE"
